[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "loeric"
authors = [{name = "Marco Amerotti", email = "amerotti@kth.se"}]
dynamic = ["version", "description"]
[tool.setuptools.dynamic]
version = {attr = "loeric.__version__"}
