[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "loeric"
authors = [{name = "Marco Amerotti", email = "amerotti@kth.se"}]
dynamic = ["version", "description"]

[tool.setuptools.dynamic]
version = {attr = "loeric.__version__"}

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["src", "."]

[tool.ruff.lint]
select = ["E", "F", "I", "D"]
extend-ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["loeric"]

[tool.setuptools.packages.find]
where = ["src"]


[project.scripts]
loeric = "loeric.__main__:main"
loeric-config = "loeric.config.__main__:main"
